language: php

sudo: required

service:
  - docker

jobs:
  include:
    - stage: build docker image
      script: make build
    - stage: test
      script:
        - make build
        - make lint
    - script:
        - make build
        - make test
