language: php

sudo: required

service:
  - docker

jobs:
  include:
    - stage: build docker image
      script:
        - docker-compose build
    - stage: test
      script: make lint
    - script: make test
