language: php

sudo: required

service:
  - docker

jobs:
  include:
    - stage: build docker image
      script:
        - docker run --rm --volume $(TRAVIS_BUILD_DIR):/app composer install
	      - docker-compose build
    - stage: test
      script:
        - docker run --rm --volume $(TRAVIS_BUILD_DIR):/app composer install
	      - docker-compose build
        - make lint
    - script:
        - docker run --rm --volume $(TRAVIS_BUILD_DIR):/app composer install
	      - docker-compose build
        - make test
