version: "3.1"
services:

  nginx:
    build: images/nginx
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
      - "80:80"

  php:
    build: images/php
    container_name: sypian-server
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html/public
    command: php-fpm
    links:
      - neo4j
    ports:
      - "9000:9000"
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_KEY: SomeRandomKey!!!
      APP_LOCALE: en
      APP_FALLBACK_LOCALE: en
      NEO4J_HOST: http://neo4j
      NEO4J_PORT: 7474
      CACHE_DRIVER: file
      QUEUE_DRIVER: sync
      GIT_BRANCH: ${TRAVIS_BRANCH-HEAD}

  neo4j:
    image: "neo4j:latest"
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ${HOME}/neo4j/data:/data
    environment:
      - "NEO4J_AUTH=none"
