version: "3.1"
services:

  php-fpm:
    build:
      context: .
    container_name: sypian-server
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
    links:
      - neo4j

  neo4j:
    image: "neo4j:latest"
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ${HOME}/neo4j/data:/data
    environment:
      - "NEO4J_AUTH=none"
